Repository maiste/eos, pull requests merged in 2019-07, with the labels that each got.

#21 docker: update eos with docker
  .travis.sh
  Dockerfile
  eos.opam
Labels: feature

#22 docker: correction
  Dockerfile
  tests/test_finder.ml
Labels: bug

#24 cmdline_hyde : add cmdline
  eos.opam
  src/core/cmdline.ml
  src/core/cmdline.mli
  src/core/dune
  src/core/main.ml
Labels: feature

#26 docs: move comparator
  docs/1_Hyde.md
  docs/2_Metamorph.md
Labels: bug

#28 Hyde
  .gitignore
  .travis.sh
  CONTRIBUTING.md
  Dockerfile
  docs/1_Hyde.md
  docs/2_Metamorph.md
  eos.opam
  src/core/cmdline.ml
  src/core/cmdline.mli
  src/core/conf.ml
  src/core/conf.mli
  src/core/dune
  src/core/finder.ml
  src/core/finder.mli
  src/core/main.ml
  src/core/monad.ml
  src/core/monad.mli
  src/core/reader.ml
  src/core/reader.mli
  tests/dune
  tests/main_test.ml
  tests/res/Read_content.test
  tests/res/conf_content1.test
  tests/res/conf_content2.test
  tests/res/conf_content3.test
  tests/test_conf.ml
  tests/test_finder.ml
  tests/test_hello.ml
  tests/test_reader.ml
Labels: release

#33 ezjsonm : convert Yojson to ezjsonm
  eos.opam
  src/core/conf.ml
  src/core/conf.mli
  src/core/dune
  tests/test_conf.ml
Labels: feature

#34 fstring: add FString
  src/core/FString.ml
  src/core/FString.mli
  tests/main_test.ml
  tests/test_fstring.ml
Labels: feature

#36 opt: add option bind
  src/core/dune
  src/core/monad.ml
  src/core/monad.mli
Labels: feature

#37 formatter : add formatter module and its test
  eos.opam
  src/core/FString.ml
  src/core/FString.mli
  src/core/cmdline.mli
  src/core/conf.ml
  src/core/conf.mli
  src/core/dune
  src/core/finder.mli
  src/core/formatter.ml
  src/core/formatter.mli
  src/core/monad.ml
  src/core/monad.mli
  tests/dune
  tests/main_test.ml
  tests/res/conf_content1.test
  tests/res/formatter_content1.test
  tests/res/formatter_content2.test
  tests/test_conf.ml
  tests/test_formatter.ml
  tests/test_fstring.ml
  tests/test_reader.ml
  tests/utilitaries.ml
Labels: feature

#38 comparator: introduce basic comparator
  src/core/comparator.ml
  src/core/comparator.mli
  tests/main_test.ml
  tests/test_comparator.ml
Labels: feature
